version: "3.5"
services:
  jaeger:
    networks:
      - backend
    image: jaegertracing/all-in-one:1.45
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - COLLECTOR_OTLP_ENABLED=true
    # ports:
      # - "14250:14250"
      # - "14268:14268"
      # - "6831:6831/udp"
      # - "16686:16686"
      # - "16685:16685"
      # - "14269:14269"
  otel_collector:
    networks:
      - backend
    image: otel/opentelemetry-collector-contrib:0.76.1
    volumes:
      - "./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    # ports:
    #   - "4317:4317"
    #   - "4318:4318"
    depends_on:
      - jaeger
  prometheus:
    networks:
      - backend
    image: prom/prometheus:v2.37.8
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    # ports:
    #   - "9090:9090"
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      # Uncomment below for development
      - SITE_ADDRESS=localhost
      # - SITE_ADDRESS=telemetry.zigtools.org
    ports:
      - "80:80"
      - "443:443"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./data/caddy/data:/data"
      - "./data/caddy/config:/config"
    networks:
      - backend
networks:
  backend: