version: "3.5"
services:
  jaeger-clickhouse:
    image: ghcr.io/jaegertracing/jaeger-clickhouse:0.13.0
    volumes:
      - jaeger-clickhouse-bin:/plugin
  clickhouse:
    image: clickhouse/clickhouse-server:23.4.2.11-alpine
    volumes:
      - clickhouse:/var/lib/clickhouse
    networks:
      - backend
    healthcheck:
      test: clickhouse status
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  jaeger:
    networks:
      - backend
    image: jaegertracing/all-in-one:1.45
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
      - "./jaeger-clickhouse.yml:/etc/jaeger/jaeger-clickhouse.yml"
      - jaeger-clickhouse-bin:/plugin
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - SPAN_STORAGE_TYPE=grpc-plugin
      - GRPC_STORAGE_PLUGIN_BINARY=/plugin/jaeger-clickhouse
      - GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE=/etc/jaeger/jaeger-clickhouse.yml
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    depends_on:
      jaeger-clickhouse:
        condition: service_started
      clickhouse:
        condition: service_healthy
  otel_collector:
    networks:
      - backend
    image: otel/opentelemetry-collector-contrib:0.76.1
    volumes:
      - "./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    depends_on:
      - jaeger
  prometheus:
    networks:
      - backend
    image: prom/prometheus:v2.37.8
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus:/prometheus"
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      - SITE_ADDRESS=${SITE_ADDRESS}
    ports:
      - "80:80"
      - "443:443"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "./data/caddy/data:/data"
      - "./data/caddy/config:/config"
    networks:
      - backend
networks:
  backend:
volumes:
  prometheus:
  clickhouse:
  jaeger-clickhouse-bin:
